# Generated by Django 5.1.7 on 2025-04-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='catogory',
        ),
        migrations.RemoveField(
            model_name='app',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='app',
            name='images',
        ),
        migrations.RemoveField(
            model_name='app',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='appimage',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appreview',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appreview',
            name='user',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='game',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('video', 'Video'), ('banner', 'Banner')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AppCategory',
        ),
        migrations.DeleteModel(
            name='AppImage',
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='AppReview',
        ),
    ]
