# Generated by Django 5.1.7 on 2025-04-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_media_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('related_type', models.CharField(choices=[('app', 'App'), ('game', 'Game'), ('book', 'Book')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='catogory',
        ),
        migrations.RemoveField(
            model_name='appimage',
            name='app',
        ),
        migrations.RemoveField(
            model_name='app',
            name='images',
        ),
        migrations.RemoveField(
            model_name='appreview',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='app',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='media',
            name='game',
        ),
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.RemoveField(
            model_name='app',
            name='Approximate_size',
        ),
        migrations.RemoveField(
            model_name='app',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='app',
            name='install_link',
        ),
        migrations.RemoveField(
            model_name='app',
            name='name',
        ),
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='download_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='app',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='app',
            name='release_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('app', 'App'), ('game', 'Game'), ('book', 'Book')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='media',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.app'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.app'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='developer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(default=1, upload_to='icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('video', 'Video'), ('banner', 'Banner')], max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='core.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppCategory',
        ),
        migrations.DeleteModel(
            name='AppImage',
        ),
        migrations.DeleteModel(
            name='AppReview',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
