# Generated by Django 5.1.7 on 2025-04-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_remove_app_catogory_remove_appimage_app_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='app',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='app',
            new_name='program',
        ),
    ]
