# Generated by Django 5.1.7 on 2025-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program_rating_count_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
