# Generated by Django 5.1.7 on 2025-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_app_catogory_remove_app_developer_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apps_library',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.program'),
        ),
    ]
